#FROM guillaumeai/tf:1.4.1  # CUDA WONT LOAD
#FROM brannondorsey/pix2pix  NOT WORKING
FROM jorgesece/pix2pix-tensorflow


#RUN git clone 
WORKDIR /model

#COPY . .
RUN git clone https://github.com/GuillaumeAI/gia-pix2pix-tensorflow-memo.git .
